accepted = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "MPL-2.0",
    "CC0-1.0",
    "Unicode-3.0",
    "OFL-1.1",
    "Ubuntu-font-1.0",
    "CDLA-Permissive-2.0",
    "GPL-2.0",
    "GPL-2.0-only",
    "GPL-2.0-or-later",
    "LGPL-2.1-or-later",
    "OpenSSL",
    "0BSD",
    "Unlicense",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
private = { ignore = true }
no-clearly-defined = true

workarounds = [
    "ring",
    "unicode-ident",
    "wasmtime",
    "chrono",
    "rustls",
    "rustix",
]
