[package]
name = "template"
version = "0.1.0"
edition = "2024"

[dependencies]
nightshade = { version = "0.6.23", features = ["tracing"] }

[features]
openxr = ["nightshade/openxr"]
steam = ["nightshade/steam"]
tracing = ["nightshade/tracing"]
