[workspace]
members = ["plugins/example-plugin", "plugins/editor-plugin"]
resolver = "2"

[package]
name = "template"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
nightshade = { version = "0.6.23", features = ["tracing"] }
wasmtime = { version = "27.0", optional = true }
wasmtime-wasi = { version = "27.0", optional = true }
anyhow = { version = "1.0", optional = true }
image = { version = "0.25", optional = true }

[features]
default = ["plugins"]
plugins = ["wasmtime", "wasmtime-wasi", "anyhow", "image"]
openxr = ["nightshade/openxr"]
steam = ["nightshade/steam"]
tracing = ["nightshade/tracing"]
